### ISSUE TITLE
PHP Notice: error when updating

### ISSUE THREAD

**Issue by bigalownz** [Maikuolan/Cronable#6]
after the last few updates of cidram
I now get this error when updating

`PHP Notice:  Undefined index: MajorVersionNotice in /var/www/cidram/vault/frontend.php on line 1672`

**Comment by Maikuolan** [comment]
Found the problem. Working on a fix for it now, and I'll reply again shortly, when I've committed the changes. Thanks for reporting this. :-)

**Comment by Maikuolan** [comment]
Fixed ([`9c9e00c`](https://github.com/CIDRAM/CIDRAM/commit/9c9e00cf30de1532a7e2e0728e1ee66d987129cb)+[`f9141bd`](https://github.com/CIDRAM/CIDRAM/commit/f9141bd7c600e17081ea3bf0620efe20613eb013)+[`7ee2e9f`](https://github.com/phpMussel/phpMussel/commit/7ee2e9f9bb72f42176f55746dbe223ce19729222)+[`4aceda2`](https://github.com/phpMussel/phpMussel/commit/4aceda23bbe99f2ac43543dc7c0fee2709aa1fcd)). :-)

**Comment by bigalownz** [comment]
i now get this

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/cidram/vault/functions.php:769
Stack trace:
#0 /var/www/cidram/vault/frontend_functions.php(720): Maikuolan\Cronable\Cronable->{closure}()
#1 /var/www/cidram/vault/frontend_functions.php(707): Maikuolan\Cronable\Cronable->{closure}()
#2 /var/www/cidram/vault/frontend.php(1790): Maikuolan\Cronable\Cronable->{closure}()
#3 /var/www/cidram/loader.php(102): require('...')
#4 /var/www/cidram/src/Cronable.php(253): require('...')
#5 /var/www/cidram/examples.php(17): Maikuolan\Cronable\Cronable->localUpdate()
#6 {main}
  thrown in /var/www/cidram/vault/functions.php on line 769
