### ISSUE TITLE
another error when updating

### ISSUE THREAD

**Issue by bigalownz** [Maikuolan/Cronable#7]
i now get this

PHP Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/cidram/vault/functions.php:769
Stack trace:
#0 /var/www/cidram/vault/frontend_functions.php(720): Maikuolan\Cronable\Cronable->{closure}()
#1 /var/www/cidram/vault/frontend_functions.php(707): Maikuolan\Cronable\Cronable->{closure}()
#2 /var/www/cidram/vault/frontend.php(1790): Maikuolan\Cronable\Cronable->{closure}()
#3 /var/www/cidram/loader.php(102): require('...')
#4 /var/www/cidram/src/Cronable.php(253): require('...')
#5 /var/www/cidram/examples.php(17): Maikuolan\Cronable\Cronable->localUpdate()
#6 {main}
thrown in /var/www/cidram/vault/functions.php on line 769

**Comment by bigalownz** [comment]
don't worry 
i found the problem it was a problem with my end with php installed on my server

**Comment by Maikuolan** [comment]
Hey. I became busy with some other things before and forgot to reply this earlier; sorry about that. Anyway, glad to hear you've figured it out. :-)
