### ISSUE TITLE
support for cidram v3

### ISSUE THREAD

**Issue by bigalownz** [Maikuolan/Cronable#9]
keep getting an error after updating to cidram v3

"An error occurred while attempting to update at [CIDRAM@/var/www/cidram/vault/loader.php]. :-(

my examples.php file is this

```

<?php
require __DIR__ . '/src/Cronable.php';


use \Maikuolan\Cronable\Cronable;

$Cronable = new Cronable;

$Cronable->execute();

$Cronable->localUpdate('CIDRAM', 'user', 'password', '/var/www/cidram/vault/loader.php', 'Everything');
echo $Cronable->Output;

```

**Comment by Maikuolan** [comment]
I might need to update something in the Cronable code, I suspect. I'll take a closer look at this later today.

**Comment by bigalownz** [comment]
any update on this please ?

thanks

**Comment by Maikuolan** [comment]
Sorry for the delay. Ended up preoccupied by other commitments. I should have something workable soon. :-)

**Comment by Maikuolan** [comment]
Partial progress. Pushed some changes, tested at my end, and can confirm that Cronable now works again properly for the `createTask()` and `execute()` methods under v3. It still doesn't work at all though for the `localUpdate()` method. Working on that now.

**Comment by Maikuolan** [comment]
I've made some changes both here and at CIDRAM v3 just now. You'll need to update to the latest available version of CIDRAM v3 via the front-end updater at least for the first time, in order to acquire those changes, and you'll need to update to the latest available version of Cronable (v1.2.3), but after that, everything should start working normally again. :-)

**Comment by bigalownz** [comment]
I don't know why but still having the same error

im running php8.2

i have cidram in /var/www/cidram/
Cronable.php is in /var/www/cidram/src/
examples.php is in /var/www/cidram/
loader.php is in /var/www/cidram/vault/

all files folders chown to www-data:www-data

**Comment by Maikuolan** [comment]
Have you created a front-end entrypoint for CIDRAM v3? If so, is the Cronable task pointing to that entrypoint? For CIDRAM v1 and v2, there was just the one entrypoint used for everything, which was `loader.php`, but for v3, we're able to create our own entrypoints however we want. We'll want to use a front-end entrypoint for Crontable tasks targeting CIDRAM v3.

**Comment by Maikuolan** [comment]
GitHub must've changed something about the way they process markdown files recently. I'm not sure what exactly, or why, but for some reason, all the internal links in the documentation seem to be broken now. :-/

I'll just link here to the anchor point in the documentation directly: https://github.com/CIDRAM/Docs/blob/master/readme.en.md#41-how-to-access-the-front-end

**Comment by bigalownz** [comment]
got it working

if i change in examples.php 

`
$Cronable->localUpdate('CIDRAM', 'user', 'password', '/var/www/cidram/vault/loader.php', 'Everything');
echo $Cronable->Output;`

to
`$Cronable->localUpdate('CIDRAM', 'user', 'password', '/var/www/cidram3.php', 'Everything');
echo $Cronable->Output;`

cidram3.php being the new front-end entry point for CIDRAM v3

and in cidram3.php i have
```
<?php
require_once '/var/www/cidram/vault/loader.php';
(new \CIDRAM\CIDRAM\FrontEnd())->view();
```
this also works
```
<?php
require_once '/var/www/cidram/vault/loader.php';
$CIDRAM = new \CIDRAM\CIDRAM\FrontEnd();
$CIDRAM->view();
```

also i notice if cidram3.php has any of these it will not work

```
<?php
require_once '/var/www/cidram/vault/loader.php';
(new \CIDRAM\CIDRAM\Core())->protect();
```
```
<?php
require_once '/var/www/cidram/vault/loader.php';
$CIDRAM = new \CIDRAM\CIDRAM\FrontEnd();
$CIDRAM->protect();
$CIDRAM->view();
```
